{{- if .Values.global.enableExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-enterprise-license
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: redis-enterprise-license
      metadataPolicy: None
    secretKey: license
  secretStoreRef:
    kind: SecretStore
    name: axp-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: redis-enterprise-license 
{{- end }}
