{{- if .Values.global.zoneAwareness }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator-ra
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch"]
{{- end }}
