apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-rec-sa
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wait-for-rec-role
  annotations:
    argocd.argoproj.io/sync-wave: "5"
rules:
  - apiGroups: ["app.redislabs.com"]
    resources: ["redisenterpriseclusters"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wait-for-rec-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: ServiceAccount
    name: wait-for-rec-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wait-for-rec-role
  apiGroup: rbac.authorization.k8s.io
