{{- if and .Values.enabled .Values.global.enableExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret-{{ .Values.name }}
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.name }}-password
      metadataPolicy: None
    secretKey: password 
  secretStoreRef:
    kind: SecretStore
    name: axp-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: redis-secret-{{ .Values.name }}
    template:
      data:
        password: '{{ "{{ .password }}" }}'
        port: "{{ .Values.databasePort }}"
        service_name: {{ .Values.name }}-headless
        service_names: {{ .Values.name }}, {{ .Values.name }}-headless
{{- end }} 
