{{- if and .Values.enabled (not .Values.global.enableExternalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret-{{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  password: "{{ .Values.secretPassword | default "changeme" }}"
  port: "{{ .Values.databasePort }}"
  service_name: {{ .Values.name }}-headless
  service_names: {{ .Values.name }}, {{ .Values.name }}-headless
{{- end }}
